"Added input validation and error handling for IDs, updated DTOs and services for clients, projects, roles, teams, and users modules."
NovaDevelopersCo/NovaDev-Backend pull request #54
Opened 2024-08-31 09:04 UTC by merdernoty

2024-08-31 12:29 UTC, Zoomish requested changes
Исправь то что я прописал и сделай обязательным поле full_name у юзера(Добавь условие в dto)

2024-08-31 12:29 UTC, Zoomish commented on src/modules/clients/clients.service.ts
> +        if (id > Number.MAX_SAFE_INTEGER) {
Думаешь у нас будет 9007199254740991 пользователей? Убери это и просто поменяй в моделях DataType.INTEGER на DataType.BIGINT

2024-08-31 12:29 UTC, Zoomish commented on src/modules/clients/clients.service.ts
> +        if (!client) {
Нет смысла каждый раз прописывать условие отсутствия. Создай middleware которая будет принимать объект и сообщение при наличии. И в ней проверяй есть ли объект и если есть возвращать его и/или сообщение

2024-08-31 22:57 UTC, merdernoty commented on src/modules/clients/clients.service.ts
> +        if (id > Number.MAX_SAFE_INTEGER) {
Да тестеровщики такой баг и написали!

2024-09-03 15:04 UTC, Zoomish approved these changes

2024-09-03 15:04 UTC, Zoomish approved these changes

2024-09-03 15:05 UTC, Zoomish approved these changes

2024-09-03 15:05 UTC, merged